nginx:
  image: nginx
  volumes:
   - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
   - "80:80"
  links:
   - application
application:
  build: .
  environment:
   - MONGO_URI=mongodb://mongo/contatooh
  links:
   - mongo
mongo:
  image: mongo
